version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket sam-deployment-11052020 --output-template-file packaged-template.yml
      - aws cloudformation package --template template.yaml --s3-bucket sam-deployment-11052020 --output-template template-export-get.json
artifacts:
  files:
    - packaged-template.yml
    - template-export-get.json