version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloworld-amit"
s3_bucket = "sam-deployment-11052020"
s3_prefix = "helloworld-amit"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"amit\""

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "helloworld-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2cngss6c59btl"
s3_prefix = "helloworld-prod"
region = "eu-central-1"
profile = "takorun"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""

[stage]
[stage.deploy]
[stage.deploy.parameters]
stack_name = "helloworld-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2cngss6c59btl"
s3_prefix = "helloworld-prod"
region = "eu-central-1"
profile = "takorun"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"stage\""

[amit]
[amit.deploy]
[amit.deploy.parameters]
stack_name = "helloworld-amit"
s3_bucket = "sam-deployment-11052020"
s3_prefix = "helloworld-amit"
region = "us-east-1"
profile = "amitkaneria"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"amit\""